[package]
name = "userns-nix"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
nix = { version = "0.29.0", features = ["fs", "user", "sched"] }
shell-escape = "0.1.5"
sys-mount = "3.0.1"
